import { MessageContextProvider } from '@/contexts/ChatMsgContext';
import './globals.css';
import { ToastMsgProvider } from '@/contexts/ToastMsgContext';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ToastNotification from '@/components/global_compns/ToastNotification';


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Workhive",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ToastMsgProvider>
                    <ToastNotification />
                    <MessageContextProvider>
                        {children}
                    </MessageContextProvider>
                </ToastMsgProvider>
            </body>
        </html>
    )
}